#!/bin/bash

if [[ -z "${1:-}" ]]; then
    label='Copyright ©2011 USHMM'
else
    label=$1
fi

font='/Users/aes9h/Downloads/fonts/Gudea/Gudea-Regular.ttf' 

if [[ ! -d jpgs ]]; then
    mkdir -p jpgs
fi
if [[ ! -d ocr ]]; then
    mkdir -p ocr
fi
if [[ ! -d marked ]]; then
    mkdir -p marked
fi

for file in *.{JPG,jpeg,jpg,gif,tif}
do

    fullname="${file##*/}"
    extension="${fullname##*.}"
    filename="${fullname%.*}"

    if [[ -f $fullname ]]; then
       ########################################################################
        # create a copy in jpg form in the jpgs directory
       ########################################################################
        if [[ "jpg" != "$extension" ]]; then
            /usr/local/bin/convert $fullname ${filename}.jpg
            newname=${filename}.jpg
            cp $newname jpgs/
        elif [[ "jpg" == "$extension" ]]; then
            cp $fullname jpgs/
        else
            echo "Skipping file $fullname."
            continue
        fi

       ######################################################################## 
        # OCR the jpg and put in ocr directory
       ######################################################################## 
       tesseract -l deu jpgs/$newname ocr/$filename

       ######################################################################## 
        # Add watermark
       ######################################################################## 
        width=$(identify -format %w jpgs/$newname) 
        height=$(identify -format %h jpgs/$newname) 
        w=$(($width * 30))
        s=$(($width/2))
        h=$(($s+$s))
        p=$(($height/35))


        # Add black text in gold box under image
        # convert \
        #     $1 \
        #     -background Gold \
        #     -pointsize $s \
        #     -font $font \
        #     -gravity south \
        #     -splice 0x$h \
        #     -annotate +0+22 "$label" \
        #     marked/$1


        # Overlay white text on dark grey transparent background
        convert \
            -background '#00000080' \
            -fill white \
            -size $s \
            -font $font \
            label:"$label" \
            miff:- | \
                composite \
                -gravity south \
                -geometry +0+3 \
                -   jpgs/$newname marked/$newname
    fi
done
